### ISSUE TITLE
Crash on exit with an Intel Arc GPU

### ISSUE THREAD

**Issue by Wagnard** [CXWorld/CapFrameX#223]
Here is the eventviewer of the crash when I exited CapFrameX
Using an Intel Arc when that happened.

Note: The application did not throw an error, I just saw in the eventlog that it crashed and got the feeling when I closed it because it lagged collecting the infos.

Application: CapFrameX.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenHardwareMonitor.Hardware.IntelGPU.IGCL.GetIgclTelemetryData(UInt32, OpenHardwareMonitor.Hardware.IntelGPU.IgclTelemetryData ByRef)
   at OpenHardwareMonitor.Hardware.IntelGPU.IntelGPU.Update()
   at CapFrameX.Sensor.SensorService+<>c.<GetSensors>b__47_0(OpenHardwareMonitor.Hardware.IHardware)
   at System.Linq.Enumerable+<SelectManyIterator>d__17`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at CapFrameX.Sensor.SensorService+<GetTimeStampedSensorValues>d__46.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.ValueTuple`2[[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[CapFrameX.Sensor.SensorService+<GetTimeStampedSensorValues>d__46, CapFrameX.Sensor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<GetTimeStampedSensorValues>d__46 ByRef)
   at CapFrameX.Sensor.SensorService.GetTimeStampedSensorValues()
   at System.Reactive.Linq.QueryLanguage+<>c__DisplayClass600_0`2[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.ValueTuple`2[[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SelectMany>b__0(Int64, System.Threading.CancellationToken)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2+TaskSelector+_[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.ValueTuple`2[[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(Int64)
   at System.Reactive.Linq.ObservableImpl.Where`1+PredicateIndexed+_[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(Int64)
   at System.Reactive.Linq.ObservableImpl.Switch`1+_+InnerObserver[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(Int64)
   at System.Reactive.IdentitySink`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(Int64)
   at System.Reactive.Linq.ObservableImpl.Timer+Periodic+_.Tick()
   at System.Reactive.Concurrency.Scheduler+<>c__67`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SchedulePeriodic>b__67_0(System.ValueTuple`2<System.__Canon,System.Action`1<System.__Canon>>)
   at System.Reactive.Concurrency.DefaultScheduler+PeriodicallyScheduledWorkItem`1+<>c[[System.ValueTuple`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Tick>b__5_0(PeriodicallyScheduledWorkItem`1<System.ValueTuple`2<System.__Canon,System.__Canon>>)
   at System.Reactive.Concurrency.AsyncLock.Wait(System.Object, System.Delegate, System.Action`2<System.Delegate,System.Object>)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by DevTechProfile** [comment]
Thanks for reporting! Interop code needs better System.AccessViolationException handling.

**Comment by riverbr** [comment]
here it normally crashes when I try to open the overlay, idk why

**Comment by DevTechProfile** [comment]
@Wagnard Please test build no 23: https://archive.capframex.com/

**Comment by Wagnard** [comment]
Sorry for late reply I'll test with build 28.
Btw what does a rebar partial support (vulkan Off) means? anything I must do to enable it or it's a hardware limitation ?

**Comment by DevTechProfile** [comment]
Vulkan off means there is an issue with the Arc driver. Performance is not affected. It's already reported to Intel.

**Comment by DevTechProfile** [comment]
Try build no >=20: https://archive.capframex.com/

It has better app shutdown handling.
